lst = ['apple','banana','watermelon','orange','kiwi']
print(lst)
print("first fruit in list is :",lst[0])
print("list has ",len(lst),"fruits")
print("removing first two items",lst[0:1])
print(lst)
print("adding papaya",lst.append('papaya'))
print(lst)
print("removing kiwi",lst.remove('kiwi'))
print(lst)
print("removing watermellon ",lst.pop(2))
print(lst)
print("sorting",lst.sort())
print(lst)
print("reversing",lst.reverse())
print(lst)
print("clearing list ",lst.clear())
print(lst)
